app_type = "server"

[server]
serve_static_files = true
is_logging = true
typescript_generation = true
port = 8080
routes_directory = "src/routes"
bindings_export_path = "/"
typescript_generation_directory = "src"

